Add rate-limiting
rawmind0/rancher-traefik pull request #61
Opened 2017-12-28 09:23 UTC by Hermsi1337

I tried to add rate-limiting capability.

Since I'm not very familiar with GO-Templating I'm not sure if I did it correct.
I simply tried to adapt the scheme of the template. ^_^

Feedback is appreciated.

PS: See #59 

Regards
Hermsi

2018-01-10 14:37 UTC, rawmind0 requested changes

2018-01-10 14:37 UTC, rawmind0 commented on README.md
> +- traefik.ratelimit.burst = < n >           # State what limit the client ip is allowed to burst up to respectively, e.g. 200
What do you think if you add a label to enable ratelimit??
```
+- traefik.ratelimit.enable = < true | false >           # Enable/disable rate limit.
```

2018-01-10 14:37 UTC, rawmind0 commented on root/opt/tools/rancher-template/tmpl/traefik.tmpl
> +    {{- end -}}
Set rate limit config based on `traefik.ratelimit.enable` label. 
Also corrected indent, other syntax errors and code refactored....

```
+      {{- $traefik_ratelimit_enable := (index $service.Labels "traefik.ratelimit.enable") -}}
+      {{- if eq $traefik_ratelimit_enable "true" -}}
+        {{- $traefik_ratelimit_period := (index $service.Labels "traefik.ratelimit.period") -}}
+        {{- $traefik_ratelimit_average := (index $service.Labels "traefik.ratelimit.average") -}}
+        {{- $traefik_ratelimit_burst := (index $service.Labels "traefik.ratelimit.burst") }}
+    [frontends.{{$service.Name}}__{{$stack.Name}}.ratelimit]
+      extractorfunc = "client.ip"
+      [frontends.{{$service.Name}}__{{$stack.Name}}.ratelimit.rateset.rateset1]
+        period = {{if gt (len $traefik_ratelimit_period) 0 -}}"{{$traefik_ratelimit_period}}s"
+                 {{- else -}} "10s"{{- end }}
+        average = {{if gt (len $traefik_ratelimit_average) 0 -}}{{$traefik_ratelimit_average}}
+                  {{- else -}}100{{- end}}
+        burst = {{if gt (len $traefik_ratelimit_burst) 0}}{{$traefik_ratelimit_burst}}
+                {{- else -}}200{{- end}}
+      {{- end -}}
```

2018-01-10 14:37 UTC, rawmind0 commented on README.md
> +- traefik.ratelimit.period = < ns >         # Replace n with desired amount of seconds in which traefik is checking the limits "average" and "burst", e.g. 10s
Don't add the `s` in the label, just the number...
```
-- traefik.ratelimit.period = < ns >         # Replace n with desired amount of seconds in which traefik is checking the limits "average" and "burst", e.g. 10s
+- traefik.ratelimit.period = < n >         # Replace n with desired amount of seconds in which traefik is checking the limits "average" and "burst", e.g. 10s
```

2018-01-10 14:39 UTC, rawmind0 commented
Hi @Hermsi1337 , thanks for the PR but the template is not working....

I've refactored and tested the code, please take a look to the changes requested....

2018-01-11 13:00 UTC, Hermsi1337 commented
Many thanks for your fixes and sorry for my syntax-failure.

I hope that everythings fine now! (=

2018-01-12 09:54 UTC, rawmind0 approved these changes

2018-01-12 09:55 UTC, rawmind0 commented
LGTM...

2018-01-12 09:55 UTC, merged

2018-01-12 10:12 UTC, rawmind0 commented
Released rawmind/rancher-traefik:1.5.0-0